# إعدادات JVM لعملية الـ Build (تقدر تقلل الرقم لو الجهاز/الترمكس محدود الذاكرة)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# مطلوب لأي مشروع Android حديث يستخدم مكتبات AndroidX
android.useAndroidX=true

# منع توليد مكتبات Support القديمة تلقائيًا بجانب AndroidX
android.enableJetifier=false

# استخدام Kotlin الرسمي في التنسيق
kotlin.code.style=official

# تفعيل non-transitive R class (أسرع في الـ build وموصى به حاليًا من AGP)
android.nonTransitiveRClass=true
